#############################################
#           📘 COURSE SERVICE API           #
#############################################

@baseUrlCourse = http://localhost:8080/api/courses
@courseId = 1

### Get Course (tanpa load manual lessons di client)
GET {{baseUrlCourse}}/{{courseId}}

### Get Lessons of a Course (trigger lazy load di service)
GET {{baseUrlCourse}}/{{courseId}}/lessons

### Create a Book With db Insertion
POST {{baseUrlCourse}}
Content-Type: application/json

{
  "name": "MANTAP"
}

### Get Courses
GET {{baseUrlCourse}}