spring.application.name=catalog-service

server.port=8081

# Resilience4j Retry Configuration
resilience4j.retry.instances.catalogRetry.max-attempts=3
resilience4j.retry.instances.catalogRetry.wait-duration=1s