apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: staging
data:
  database.url: "jdbc:postgresql://postgres-staging:5432/bookdb"
  kafka.bootstrap.servers: "kafka-staging:9092"
  logging.level: "INFO"
  server.port: "8080"