apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: prod
data:
  database.url: "jdbc:postgresql://postgres-prod:5432/bookdb"
  kafka.bootstrap.servers: "kafka-prod:9092"
  logging.level: "WARN"
  server.port: "8080"