apiVersion: v1
kind: Secret
metadata:
  name: book-service-secret
  namespace: dev
type: Opaque
data:
  # Base64 encoded values
  database.username: YWRtaW4=           # admin
  database.password: cGFzc3dvcmQxMjM=   # password123
  kafka.api.key: a2Fma2Ffa2V5XzEyMw==   # kafka_key_123
stringData:
  # Plain text - Kubernetes will encode automatically
  api.token: "my-secret-token-12345"
  jwt.secret: "my-jwt-secret-key"